# Generated by Django 5.1.4 on 2025-03-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_wallettransaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='user',
        ),
    ]
