# Generated by Django 5.1.4 on 2025-02-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_rename_active_coupon_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
    ]
