# Generated by Django 5.1.4 on 2025-02-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_userprofile_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='max_amount',
            new_name='max_discount',
        ),
    ]
