# Generated by Django 5.1.4 on 2025-03-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0010_remove_coupon_user_coupon_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
    ]
