# Generated by Django 5.1.4 on 2025-03-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0011_remove_coupon_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
