# Generated by Django 5.1.4 on 2025-03-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0013_couponusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_used',
        ),
    ]
