# Generated by Django 5.1.4 on 2025-03-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0014_remove_coupon_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='final_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
