# Generated by Django 5.1.4 on 2025-03-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0015_couponusage_final_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
