# Generated by Django 5.1.4 on 2024-12-31 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_otpverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 17, 20, 46, 371395, tzinfo=datetime.timezone.utc)),
        ),
    ]
