# Generated by Django 5.1.4 on 2025-01-02 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_alter_otpverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 10, 2, 56, 634138, tzinfo=datetime.timezone.utc)),
        ),
    ]
