# Generated by Django 5.1.4 on 2025-01-02 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0014_alter_otpverification_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 17, 38, 32, 620207, tzinfo=datetime.timezone.utc)),
        ),
    ]
