# Generated by Django 5.1.4 on 2025-01-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0027_alter_otpverification_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_expiry',
            field=models.CharField(blank=True, null=True),
        ),
    ]
