# Generated by Django 5.1.4 on 2025-03-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
