# Generated by Django 5.1.4 on 2025-01-17 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 24, 16, 11, 31, 114915, tzinfo=datetime.timezone.utc)),
        ),
    ]
