# Generated by Django 5.1.4 on 2025-01-17 16:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='date_of_order',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 24, 16, 33, 18, 908977, tzinfo=datetime.timezone.utc)),
        ),
    ]
