# Generated by Django 5.1.4 on 2025-01-19 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userdetails_estimated_delivery_orderdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 26, 10, 17, 14, 786725, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 26, 10, 17, 14, 786097, tzinfo=datetime.timezone.utc)),
        ),
    ]
