# Generated by Django 5.1.4 on 2025-01-19 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_orderdetails_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 26, 11, 8, 41, 469842, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 26, 11, 8, 41, 469172, tzinfo=datetime.timezone.utc)),
        ),
    ]
