# Generated by Django 5.1.4 on 2025-01-19 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_orderdetails_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.date(2025, 1, 26)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 26, 14, 51, 3, 86241, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
