# Generated by Django 5.1.4 on 2025-01-20 05:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productattribute'),
        ('user', '0007_remove_orderdetails_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_id',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.date(2025, 1, 27)),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 27, 5, 0, 55, 113686, tzinfo=datetime.timezone.utc)),
        ),
    ]
