# Generated by Django 5.1.4 on 2025-01-20 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_orderdetails_product_id_orderdetails_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 27, 5, 19, 48, 934331, tzinfo=datetime.timezone.utc)),
        ),
    ]
