# Generated by Django 5.1.4 on 2025-01-20 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_orderdetails_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 27, 17, 43, 52, 950856, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
