# Generated by Django 5.1.4 on 2025-01-20 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_userdetails_estimated_delivery_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 27, 18, 15, 2, 422319, tzinfo=datetime.timezone.utc)),
        ),
    ]
