# Generated by Django 5.1.4 on 2025-01-21 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 28, 4, 56, 12, 658828, tzinfo=datetime.timezone.utc)),
        ),
    ]
