# Generated by Django 5.1.4 on 2025-01-21 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='PENDING', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 28, 6, 10, 5, 520291, tzinfo=datetime.timezone.utc)),
        ),
    ]
