# Generated by Django 5.1.4 on 2025-01-21 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_order_payment_status_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 28, 7, 11, 10, 597127, tzinfo=datetime.timezone.utc)),
        ),
    ]
