# Generated by Django 5.1.4 on 2025-01-21 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 28, 7, 16, 34, 246433, tzinfo=datetime.timezone.utc)),
        ),
    ]
