# Generated by Django 5.1.4 on 2025-01-21 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 28, 14, 39, 4, 218195, tzinfo=datetime.timezone.utc)),
        ),
    ]
