# Generated by Django 5.1.4 on 2025-01-22 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 29, 3, 45, 58, 903484, tzinfo=datetime.timezone.utc)),
        ),
    ]
