# Generated by Django 5.1.4 on 2025-01-23 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 30, 9, 21, 19, 926754, tzinfo=datetime.timezone.utc)),
        ),
    ]
