# Generated by Django 5.1.4 on 2025-01-24 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 7, 2, 28, 749670, tzinfo=datetime.timezone.utc)),
        ),
    ]
