# Generated by Django 5.1.4 on 2025-01-24 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 7, 51, 4, 402338, tzinfo=datetime.timezone.utc)),
        ),
    ]
