# Generated by Django 5.1.4 on 2025-01-24 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 8, 3, 18, 192473, tzinfo=datetime.timezone.utc)),
        ),
    ]
