# Generated by Django 5.1.4 on 2025-01-25 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 1, 10, 31, 12, 103359, tzinfo=datetime.timezone.utc)),
        ),
    ]
