# Generated by Django 5.1.4 on 2025-01-25 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 1, 11, 57, 12, 40169, tzinfo=datetime.timezone.utc)),
        ),
    ]
