# Generated by Django 5.1.4 on 2025-01-25 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 1, 16, 34, 35, 368279, tzinfo=datetime.timezone.utc)),
        ),
    ]
