# Generated by Django 5.1.4 on 2025-01-25 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 1, 19, 12, 38, 95559, tzinfo=datetime.timezone.utc)),
        ),
    ]
