# Generated by Django 5.1.4 on 2025-01-26 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 9, 21, 36, 918529, tzinfo=datetime.timezone.utc)),
        ),
    ]
