# Generated by Django 5.1.4 on 2025-01-26 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 13, 46, 58, 749455, tzinfo=datetime.timezone.utc)),
        ),
    ]
