# Generated by Django 5.1.4 on 2025-01-26 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 14, 44, 24, 987272, tzinfo=datetime.timezone.utc)),
        ),
    ]
