# Generated by Django 5.1.4 on 2025-01-26 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 19, 25, 55, 702036, tzinfo=datetime.timezone.utc)),
        ),
    ]
