# Generated by Django 5.1.4 on 2025-01-27 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 3, 2, 21, 37, 871310, tzinfo=datetime.timezone.utc)),
        ),
    ]
