# Generated by Django 5.1.4 on 2025-01-27 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Order Pending', 'Order Pending'), ('Order Confirmed', 'Order Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Requested Return', 'Requested Return'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Order Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 3, 4, 0, 25, 405050, tzinfo=datetime.timezone.utc)),
        ),
    ]
