# Generated by Django 5.1.4 on 2025-01-27 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 3, 6, 24, 38, 468720, tzinfo=datetime.timezone.utc)),
        ),
    ]
