# Generated by Django 5.1.4 on 2025-02-05 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_alter_userdetails_estimated_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Unknown User', max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='estimated_delivery',
            field=models.DateField(default=datetime.datetime(2025, 2, 12, 7, 49, 24, 700459, tzinfo=datetime.timezone.utc)),
        ),
    ]
