# Generated by Django 5.1.4 on 2025-02-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
