# Generated by Django 5.1.4 on 2025-02-24 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_alter_coupon_code'),
        ('orders', '0007_orderitem_discount_amount_orderitem_final_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon'),
        ),
    ]
