# Generated by Django 5.1.4 on 2025-03-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total',
            new_name='subtotal',
        ),
    ]
