# Generated by Django 5.1.4 on 2025-03-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_subtotal_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Wallet', 'Wallet'), ('Razorpay', 'Razorpay'), ('Cash on Delivery', 'Cash on Delivery')], default='Credit Card', max_length=20),
        ),
    ]
