# Generated by Django 5.1.4 on 2025-03-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
